### PR TITLE
Compatibility layer update2

### PR DESCRIPTION
**Pull request by lorforlinux**
@jadonk @RobertCNelson please review my code :)

This update includes these major changes,
1. Removed `*gpio_input_pin` pinmux nodes for BBB and BBAI.
2. Added remaining PRU pinmux nodes (eCAP and UART).
3. Created bone_emmc label and compatible DT overlay.
4. New gpio_* macros for each Header pins.
5. Updated BBAI bone-pinmux-helper nodes.
6. Updated comments to point this repo (v4.19.x.ti-overlays).
7. Replace CTAG SW 16ch (for v4.4) with CTAG SW 8ch for (v4.14 and above).
8. Updated DT overlay names e.x. ECAP -> eCAP.

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Why a bbai emmc? The pins don't conflict?

**Comment by lorforlinux** [comment]
No, the pins don't conflict. They pins are available on BBAI but on BBB they are used by the onboard eMMC.
Please see this -> https://elinux.org/Beagleboard:BeagleBone_cape_interface_spec#eMMC

**Comment by jadonk** [comment]
should probably add SD and an SDIO example (like WiFi).

**Comment by lorforlinux** [comment]
@jadonk okay, I am working on the compatibility documentation at this moment. It would be very nice if you could take a look at the [cape interface spec page](https://elinux.org/Beagleboard:BeagleBone_cape_interface_spec) and create some TODO tasks for whatever needs to be done but seems missing at this moment. I will try to complete those tasks ASAP ;)

**Pull request merged**
