### PR TITLE
Add BeagleBone AI P9 header pinmux nodes

### PR DESCRIPTION
**Pull request by deepaklorkhatri007**
This is a follow up pull request to #8 :)

### CODE REVIEW

**Comment by RobertCNelson** [comment]
```
  Checking pull-requests...

    Checking pull request #9
    Submitted from fork, skipping
```

**Comment by RobertCNelson** [comment]
hehe, there we go...^

**Comment by RobertCNelson** [comment]
yay, authomation works. ;) thanks for helping test... (and merged)

**Comment by deepaklorkhatri007** [comment]
Wooh! you are quick! thanks, @RobertCNelson :)

**Comment by deepaklorkhatri007** [comment]
@RobertCNelson I have created a new pull request for P9 header node values #10 :)

**Pull request merged**
