### PR TITLE
Compatibility layer update1

### PR DESCRIPTION
**Pull request by lorforlinux**
@jadonk @RobertCNelson please review my code :) 

This updated majorly includes new features and updated like,
1. Added nodes and compatible DT overlays for eQEP, McASP, and eCAP.
2. Updated old compatible overlays.

### CODE REVIEW

**Comment by RobertCNelson** [comment]
@lorforlinux does ethernet work for you, for some reason it's failnig...

**Comment by RobertCNelson** [comment]
I just noticed, it stopped at some point in the last week or two. ;)

**Comment by lorforlinux** [comment]
okay, do you think the compatibility layer created this issue?

**Comment by RobertCNelson** [comment]
Found it!  A2 has a new PHY! A1 board works just fine... doh..

**Comment by lorforlinux** [comment]
ohh okay :+1:

**Pull request merged**
