### PR TITLE
Add BeagleBone AI P9 header pinmux nodes.

### PR DESCRIPTION
**Pull request by deepaklorkhatri007**
follow up pull request to #8 and #9 :)

### CODE REVIEW

**Comment by RobertCNelson** [comment]
```
  DTC     src/arm/am5729-beagleboneai-roboticscape.dtb
In file included from src/arm/am5729-beagleboneai.dts:2406,
                 from src/arm/am5729-beagleboneai-roboticscape.dts:8:
src/arm/dra7-ipu-common-early-boot.dtsi:49: error: unterminated argument list invoking macro "DRA7XX_CORE_IOPAD"
 };
```

**Comment by deepaklorkhatri007** [comment]
@RobertCNelson, I have fixed the issue, it was due to i2c nodes I created for some pins with multiple gpio attached. removed the code and it is compiling fine now. I installed the DTC compiler but I forgot to compile before uploading, I will make sure to compile before pushing.

**Comment by RobertCNelson** [comment]
@deepaklorkhatri007 no worries, 92 pins can be fun to edit. ;) all merged..

**Comment by deepaklorkhatri007** [comment]
@RobertCNelson, can we use `bone-pinmux-helper` binding with AM572x SoC?

**Pull request merged**
