### PR TITLE
Rework Devicetree for the Beaglebone Blue 

### PR DESCRIPTION
**Pull request by ghost**
After checking out the recent Minimal Debian 12.x Image for the BeagleboneBlue, it became clear that the device tree is broken. This patch intends to fix the issues.

At the point of this writing.
The Power Button functionality was restored.

Other things are to follow.
- PWM
- Quad Encoders
...

This patch correlates with a tbd patch for the librobotcontrol which is also broken since Kernel 5.X!

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Yes, the color of the LED is wrong.. this is an userspace abi going back to 3.8x era bbb scripts..  otherwise just to confirm, on power down all LEDs turn off?

**Comment by ghost** [comment]
> Yes, the color of the LED is wrong.. this is an userspace abi going back to 3.8x era bbb scripts.. otherwise just to confirm, on power down all LEDs turn off?

yes, all leds except for the PWR_LED (3.3V Indicator / blue) next to the 12V connector and if 12V is powered the CHG_LED (charger enabled / green) next to the Battery JST connector is on.

Expert Question: Why is the property `ti,pmic-shutdown-controller;` still in [am335x-osd335x-common.dtsi](https://github.com/beagleboard/BeagleBoard-DeviceTrees/blob/v5.10.x-ti-unified/src/arm/am335x-osd335x-common.dtsi#L64) if it can break certain boards? Why was it not removed?

Current status:
Together with the [naming scheme change of uarts](https://github.com/beagleboard/librobotcontrol/compare/master...menschel:librobotcontrol:dev_bblue_debian12) in librobotcontrol, 


I reached this output.

```
$ rc_test_drivers 

Kernel: 5.10.168-ti-r73
BeagleBoard.org Debian Bookworm Minimal Image 2023-10-07
Debian: 12.2

PASSED: gpio 0
PASSED: gpio 1
PASSED: gpio 2
PASSED: gpio 3
ERROR:  ti-pwm driver not loaded for hrpwm0
ERROR:  ti-pwm driver not loaded for hrpwm1
ERROR:  ti-pwm driver not loaded for hrpwm2
ERROR:  ti-eqep driver not loaded for eqep0
ERROR:  ti-eqep driver not loaded for eqep1
ERROR:  ti-eqep driver not loaded for eqep2
PASSED: pru-rproc
PASSED: uart1
PASSED: uart2
PASSED: uart4
PASSED: uart5
PASSED: i2c1
PASSED: i2c2
ERROR: spi driver not loaded
PASSED: LED
PASSED: ADC iio

Currently running on a:
MODEL_BB_BLUE
Robot Control library Version:
1.0.5
```
 I'm left with:

- PWM (No Documentation found on driver)
- Quad Encoders  (Also no Documentation found on driver)
- SPI ( Spidev) but recent Kernel Docs say it should not be used in DTS ?!

**Comment by ghost** [comment]
OK, the changes to get this far were fairly trivial. 

```
$ rc_test_drivers 

Kernel: 5.10.168-ti-r73
BeagleBoard.org Debian Bookworm Minimal Image 2023-10-07
Debian: 12.2

PASSED: gpio 0
PASSED: gpio 1
PASSED: gpio 2
PASSED: gpio 3
ERROR:  ti-pwm driver not loaded for hrpwm0
ERROR:  ti-pwm driver not loaded for hrpwm1
ERROR:  ti-pwm driver not loaded for hrpwm2
ERROR:  ti-eqep driver not loaded for eqep0
ERROR:  ti-eqep driver not loaded for eqep1
ERROR:  ti-eqep driver not loaded for eqep2
PASSED: pru-rproc
PASSED: uart1
PASSED: uart2
PASSED: uart4
PASSED: uart5
PASSED: i2c1
PASSED: i2c2
PASSED: spi
PASSED: LED
PASSED: ADC iio

Currently running on a:
MODEL_BB_BLUE
Robot Control library Version:
1.0.5
```

But what about the PWM and the Quad Encoders ?
Is this a missing driver or a devicetree issue?
I see nothing in dmesg or via 

```
# find /sys/ -name "*pwm*"                                     
/sys/kernel/tracing/events/pwm
/sys/kernel/tracing/events/pwm/pwm_apply
/sys/kernel/tracing/events/pwm/pwm_get
/sys/kernel/debug/clk/ehrpwm0_tbclk
/sys/kernel/debug/clk/ehrpwm1_tbclk
/sys/kernel/debug/clk/ehrpwm2_tbclk
/sys/kernel/debug/tracing/events/pwm
/sys/kernel/debug/tracing/events/pwm/pwm_apply
/sys/kernel/debug/tracing/events/pwm/pwm_get
/sys/kernel/debug/pwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss
/sys/class/pwm
/sys/firmware/devicetree/base/__symbols__/ehrpwm2
/sys/firmware/devicetree/base/__symbols__/epwmss2
/sys/firmware/devicetree/base/__symbols__/ehrpwm0
/sys/firmware/devicetree/base/__symbols__/epwmss0
/sys/firmware/devicetree/base/__symbols__/ehrpwm1_tbclk
/sys/firmware/devicetree/base/__symbols__/ehrpwm1
/sys/firmware/devicetree/base/__symbols__/epwmss1
/sys/firmware/devicetree/base/__symbols__/ehrpwm2_tbclk
/sys/firmware/devicetree/base/__symbols__/ehrpwm0_tbclk
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0/pwm@100
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0/pwm@100/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0/pwm@200
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0/pwm@200/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0/pwm@100
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0/pwm@100/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0/pwm@200
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0/pwm@200/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0/pwm@100
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0/pwm@100/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0/pwm@200
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0/pwm@200/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@0/target-module@46000/timer@0/ti,timer-pwm
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@0/target-module@48000/timer@0/ti,timer-pwm
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@0/target-module@4a000/timer@0/ti,timer-pwm
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@0/target-module@44000/timer@0/ti,timer-pwm
/sys/firmware/devicetree/base/ocp/interconnect@44c00000/segment@200000/target-module@10000/scm@0/scm_conf@0/clocks/ehrpwm1_tbclk@44e10664
/sys/firmware/devicetree/base/ocp/interconnect@44c00000/segment@200000/target-module@10000/scm@0/scm_conf@0/clocks/ehrpwm0_tbclk@44e10664
/sys/firmware/devicetree/base/ocp/interconnect@44c00000/segment@200000/target-module@10000/scm@0/scm_conf@0/clocks/ehrpwm2_tbclk@44e10664
/sys/bus/platform/devices/48300000.epwmss
/sys/bus/platform/devices/48304000.epwmss
/sys/bus/platform/devices/48302000.epwmss
/sys/bus/platform/drivers/pwm-regulator
/sys/bus/platform/drivers/pwmss
/sys/bus/platform/drivers/pwmss/48300000.epwmss
/sys/bus/platform/drivers/pwmss/48304000.epwmss
/sys/bus/platform/drivers/pwmss/48302000.epwmss
/sys/bus/platform/drivers/pwm-backlight
/sys/bus/platform/drivers/omap-dmtimer-pwm
/sys/bus/platform/drivers/ehrpwm
/sys/bus/i2c/drivers/pca9685-pwm
```
and  `/sys/class/pwm/` is empty

Please advise.

**Comment by ghost** [comment]
ok, PWMs are both DT Issue and librobotcontrol issue.

Do I need to set PINs ?
The pins from schematic are not mappable in [list](https://github.com/selsinork/beaglebone-black-pinmux/blob/master/pinmux.ods) to anything with pwm.

Do I need to enable ECAP as well?

```
# find /sys/ -name "*pwm*"                                     
/sys/kernel/tracing/events/pwm
/sys/kernel/tracing/events/pwm/pwm_apply
/sys/kernel/tracing/events/pwm/pwm_get
/sys/kernel/debug/clk/ehrpwm0_tbclk
/sys/kernel/debug/clk/ehrpwm1_tbclk
/sys/kernel/debug/clk/ehrpwm2_tbclk
/sys/kernel/debug/tracing/events/pwm
/sys/kernel/debug/tracing/events/pwm/pwm_apply
/sys/kernel/debug/tracing/events/pwm/pwm_get
/sys/kernel/debug/pwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss/48300200.pwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss/48300200.pwm/pwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss/48300200.pwm/pwm/pwmchip0
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss/48300200.pwm/pwm/pwmchip0/pwm1
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss/48300200.pwm/pwm/pwmchip0/pwm0
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss/48300200.pwm/pwm/pwmchip0/npwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss/48302200.pwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss/48302200.pwm/pwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss/48302200.pwm/pwm/pwmchip2
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss/48302200.pwm/pwm/pwmchip2/pwm1
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss/48302200.pwm/pwm/pwmchip2/pwm0
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss/48302200.pwm/pwm/pwmchip2/npwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss/48304200.pwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss/48304200.pwm/pwm
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss/48304200.pwm/pwm/pwmchip4
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss/48304200.pwm/pwm/pwmchip4/pwm1
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss/48304200.pwm/pwm/pwmchip4/pwm0
/sys/devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss/48304200.pwm/pwm/pwmchip4/npwm
/sys/class/pwm
/sys/class/pwm/pwmchip0
/sys/class/pwm/pwmchip4
/sys/class/pwm/pwmchip2
/sys/firmware/devicetree/base/__symbols__/ehrpwm2
/sys/firmware/devicetree/base/__symbols__/epwmss2
/sys/firmware/devicetree/base/__symbols__/ehrpwm0
/sys/firmware/devicetree/base/__symbols__/epwmss0
/sys/firmware/devicetree/base/__symbols__/ehrpwm1_tbclk
/sys/firmware/devicetree/base/__symbols__/ehrpwm1
/sys/firmware/devicetree/base/__symbols__/epwmss1
/sys/firmware/devicetree/base/__symbols__/ehrpwm2_tbclk
/sys/firmware/devicetree/base/__symbols__/ehrpwm0_tbclk
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0/pwm@100
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0/pwm@100/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0/pwm@200
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@2000/epwmss@0/pwm@200/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0/pwm@100
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0/pwm@100/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0/pwm@200
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@0/epwmss@0/pwm@200/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0/pwm@100
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0/pwm@100/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0/pwm@200
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@300000/target-module@4000/epwmss@0/pwm@200/#pwm-cells
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@0/target-module@46000/timer@0/ti,timer-pwm
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@0/target-module@48000/timer@0/ti,timer-pwm
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@0/target-module@4a000/timer@0/ti,timer-pwm
/sys/firmware/devicetree/base/ocp/interconnect@48000000/segment@0/target-module@44000/timer@0/ti,timer-pwm
/sys/firmware/devicetree/base/ocp/interconnect@44c00000/segment@200000/target-module@10000/scm@0/scm_conf@0/clocks/ehrpwm1_tbclk@44e10664
/sys/firmware/devicetree/base/ocp/interconnect@44c00000/segment@200000/target-module@10000/scm@0/scm_conf@0/clocks/ehrpwm0_tbclk@44e10664
/sys/firmware/devicetree/base/ocp/interconnect@44c00000/segment@200000/target-module@10000/scm@0/scm_conf@0/clocks/ehrpwm2_tbclk@44e10664
/sys/bus/platform/devices/48300000.epwmss
/sys/bus/platform/devices/48300200.pwm
/sys/bus/platform/devices/48304200.pwm
/sys/bus/platform/devices/48304000.epwmss
/sys/bus/platform/devices/48302200.pwm
/sys/bus/platform/devices/48302000.epwmss
/sys/bus/platform/drivers/pwm-regulator
/sys/bus/platform/drivers/pwmss
/sys/bus/platform/drivers/pwmss/48300000.epwmss
/sys/bus/platform/drivers/pwmss/48304000.epwmss
/sys/bus/platform/drivers/pwmss/48302000.epwmss
/sys/bus/platform/drivers/pwm-backlight
/sys/bus/platform/drivers/omap-dmtimer-pwm
/sys/bus/platform/drivers/ehrpwm
/sys/bus/platform/drivers/ehrpwm/48300200.pwm
/sys/bus/platform/drivers/ehrpwm/48304200.pwm
/sys/bus/platform/drivers/ehrpwm/48302200.pwm
/sys/bus/i2c/drivers/pca9685-pwm
```

**Comment by ghost** [comment]
ok, found something, I can work with this...
https://github.com/beagleboard/librobotcontrol/blob/master/device_tree/dtb-4.14-ti/am335x-boneblue.dts#L170C5-L170C5

**Comment by ghost** [comment]
OK, I believe I'm almost through with the change in devicetree.
It would be nice if someone with knowledge about the pcb would review my changes.

In the meanwhile, I'll work on librobotcontrol, at least until the test_rc_XYZ examples work for me. Job for next weekend though.

**Comment by ghost** [comment]
First test of the Servos is failing. Moves once on init but does neither sweep nor move after the initial pulse.
Is it possible that my pin assignments are not taken into account?

**Comment by RobertCNelson** [comment]
Awesome @menschel merged everything up on this pull.  only change is the led.. one option we did on mainline (pocketbeagle) was this.. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/arch/arm/boot/dts/ti/omap/am335x-pocketbeagle.dts?id=909ed2f52a06ac65d397e6c9efdba3a6260cb0b5  

```
 		led-usr0 {
 			label = "beaglebone:green:usr0";
+			color = <LED_COLOR_ID_BLUE>;
+			function = LED_FUNCTION_HEARTBEAT;
 			gpios = <&gpio1 21 GPIO_ACTIVE_HIGH>;
 			linux,default-trigger = "heartbeat";
 			default-state = "off";
```

left the "abi" label problem and used the 'color' function.. i'm pretty sure the led-<> maintainer wants to nuke label at somepoint.. 

spidev: yes mainline wants to get rid of the spidev compatible, i've mostly moved to using `compatible = "rohm,dh2228fv";` as that works all the way back to 3.8.x, exactly the same with no kernel warnings.. pushed this: https://git.beagleboard.org/beagleboard/BeagleBoard-DeviceTrees/-/commit/0d2391160e3ef113f105a97047a4811179346da9

```ti,pmic-shutdown-controller``` this has always been fun.. i've got to dig out in my mind on this one.. i believe it had to do with a 32khz clock on the blue/pocketbeagle with the rtc.. the main problem, on shutdown, system would come down, but when switching to the rtc unit for final shutdown it would just lock up.. so power rails would stay up.. honestly this is really from 4.4/4.9/4.19 era, so there is a chance the clocks now work fine..

ti-eqep : this is the fun one, we had a beagle user develop a driver back in 3.8.x era, and we used that forever, i'd say around 5.4 a real 'counter' driver was pushed mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/counter?h=v6.7-rc5 (idea is the same, interfaces different).. the other fun, the pru 'emulates' the old ti-eqep for one of the encoders..

pwm: this is abi change, with our complex pwm options, udev would always fail to send any uevents, so we carried this patch for ever.. https://github.com/RobertCNelson/ti-linux-kernel-dev/blob/ti-linux-4.19.y/patches/drivers/pwm/0002-pwm-Create-device-class-for-pwm-channels.patch  in the 5.x era, finally someone else had the same problem.. only the solution posted for mainline was different then this old 2016 patch.. so the directories are different..

pwm-2... since pwm's been a pain we do have symlinks on startup helping user find specific pwm's.. so this might help you in librobotcontrol: https://github.com/rcn-ee/repos/blob/master/bb-customizations/suite/bullseye/debian/bb-symlinks

PS, thank you so much for looking at the Blue, i've had a bad habit of blowing this particular board up so often i just don't touch it anymore.. (usart0 isn't isolated when no power is applied)..

Regards,

**Comment by RobertCNelson** [comment]
4.19.94-ti-r74
```
debian@21-am335x-bbb:~$ tree -h /sys/class/pwm/
/sys/class/pwm/
├── [   0]  pwm-0:0 -> ../../devices/platform/ocp/48300000.epwmss/48300100.ecap/pwm/pwmchip0/pwm-0:0
├── [   0]  pwm-1:0 -> ../../devices/platform/ocp/48300000.epwmss/48300200.pwm/pwm/pwmchip1/pwm-1:0
├── [   0]  pwm-1:1 -> ../../devices/platform/ocp/48300000.epwmss/48300200.pwm/pwm/pwmchip1/pwm-1:1
├── [   0]  pwm-3:0 -> ../../devices/platform/ocp/48302000.epwmss/48302100.ecap/pwm/pwmchip3/pwm-3:0
├── [   0]  pwm-4:0 -> ../../devices/platform/ocp/48302000.epwmss/48302200.pwm/pwm/pwmchip4/pwm-4:0
├── [   0]  pwm-4:1 -> ../../devices/platform/ocp/48302000.epwmss/48302200.pwm/pwm/pwmchip4/pwm-4:1
├── [   0]  pwm-6:0 -> ../../devices/platform/ocp/48304000.epwmss/48304100.ecap/pwm/pwmchip6/pwm-6:0
├── [   0]  pwm-7:0 -> ../../devices/platform/ocp/48304000.epwmss/48304200.pwm/pwm/pwmchip7/pwm-7:0
├── [   0]  pwm-7:1 -> ../../devices/platform/ocp/48304000.epwmss/48304200.pwm/pwm/pwmchip7/pwm-7:1
├── [   0]  pwmchip0 -> ../../devices/platform/ocp/48300000.epwmss/48300100.ecap/pwm/pwmchip0
├── [   0]  pwmchip1 -> ../../devices/platform/ocp/48300000.epwmss/48300200.pwm/pwm/pwmchip1
├── [   0]  pwmchip3 -> ../../devices/platform/ocp/48302000.epwmss/48302100.ecap/pwm/pwmchip3
├── [   0]  pwmchip4 -> ../../devices/platform/ocp/48302000.epwmss/48302200.pwm/pwm/pwmchip4
├── [   0]  pwmchip6 -> ../../devices/platform/ocp/48304000.epwmss/48304100.ecap/pwm/pwmchip6
└── [   0]  pwmchip7 -> ../../devices/platform/ocp/48304000.epwmss/48304200.pwm/pwm/pwmchip7

15 directories, 0 files
```
```
debian@21-am335x-bbb:~$ tree -h /sys/class/pwm/pwm-0\:0/
/sys/class/pwm/pwm-0:0/
├── [4.0K]  capture
├── [   0]  device -> ../../pwmchip0
├── [4.0K]  duty_cycle
├── [4.0K]  enable
├── [4.0K]  period
├── [4.0K]  polarity
├── [   0]  power
│   ├── [4.0K]  async
│   ├── [4.0K]  autosuspend_delay_ms
│   ├── [4.0K]  control
│   ├── [4.0K]  runtime_active_kids
│   ├── [4.0K]  runtime_active_time
│   ├── [4.0K]  runtime_enabled
│   ├── [4.0K]  runtime_status
│   ├── [4.0K]  runtime_suspended_time
│   └── [4.0K]  runtime_usage
├── [   0]  subsystem -> ../../../../../../../../class/pwm
└── [4.0K]  uevent

3 directories, 15 files
```


5.10.168-ti-r73
```
debian@23-am335x-bbb:~$ tree -h /sys/class/pwm/
/sys/class/pwm/
├── [   0]  pwmchip0 -> ../../devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss/48300100.pwm/pwm/pwmchip0
├── [   0]  pwmchip1 -> ../../devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss/48302100.pwm/pwm/pwmchip1
├── [   0]  pwmchip2 -> ../../devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss/48304100.pwm/pwm/pwmchip2
├── [   0]  pwmchip3 -> ../../devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48300000.target-module/48300000.epwmss/48300200.pwm/pwm/pwmchip3
├── [   0]  pwmchip5 -> ../../devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48302000.target-module/48302000.epwmss/48302200.pwm/pwm/pwmchip5
└── [   0]  pwmchip7 -> ../../devices/platform/ocp/48000000.interconnect/48000000.interconnect:segment@300000/48304000.target-module/48304000.epwmss/48304200.pwm/pwm/pwmchip7

6 directories, 0 files
```
```
debian@23-am335x-bbb:~$ tree -h /sys/class/pwm/pwmchip0/
/sys/class/pwm/pwmchip0/
├── [   0]  device -> ../../../48300100.pwm
├── [4.0K]  export
├── [4.0K]  npwm
├── [   0]  power
│   ├── [4.0K]  async
│   ├── [4.0K]  autosuspend_delay_ms
│   ├── [4.0K]  control
│   ├── [4.0K]  runtime_active_kids
│   ├── [4.0K]  runtime_active_time
│   ├── [4.0K]  runtime_enabled
│   ├── [4.0K]  runtime_status
│   ├── [4.0K]  runtime_suspended_time
│   └── [4.0K]  runtime_usage
├── [   0]  pwm0
│   ├── [4.0K]  capture
│   ├── [4.0K]  duty_cycle
│   ├── [4.0K]  enable
│   ├── [4.0K]  period
│   ├── [4.0K]  polarity
│   ├── [   0]  power
│   │   ├── [4.0K]  async
│   │   ├── [4.0K]  autosuspend_delay_ms
│   │   ├── [4.0K]  control
│   │   ├── [4.0K]  runtime_active_kids
│   │   ├── [4.0K]  runtime_active_time
│   │   ├── [4.0K]  runtime_enabled
│   │   ├── [4.0K]  runtime_status
│   │   ├── [4.0K]  runtime_suspended_time
│   │   └── [4.0K]  runtime_usage
│   └── [4.0K]  uevent
├── [   0]  subsystem -> ../../../../../../../../../../class/pwm
├── [4.0K]  uevent
└── [4.0K]  unexport

5 directories, 28 files
```

**Comment by ghost** [comment]
I just found the [initial commit ](https://git.ti.com/cgit/ti-linux-kernel/ti-linux-kernel/commit/arch/arm/boot/dts/am335x-bone-common.dtsi?h=linux-5.10.y&id=7a6cb0abe1aa63334f3ded6d2b6c8eca80e72302)for `ti,pmic-shutdown-controller`.

It appears the property should be present. Or do we run "RTC-only" Mode? There is a 32kHz crystal on OSC1 according to schematics.

**Comment by RobertCNelson** [comment]
Here's part of the fun... the rtc clock source can only be changed in u-boot:

https://git.beagleboard.org/beagleboard/u-boot/-/commit/a4490be7f1ea57b7bfc8eab45e8c39114290a7b0

For the pocketbeagle, we force the internal 32khz rtc clock: SEL_32KCLK_SRC

Then on the  blue we also force the internal 32khz; https://git.beagleboard.org/beagleboard/u-boot/-/commit/bdbb513d002649eacc980c97c9335146e740385b  wonder if my board was always just bad..

this first name also has to line up with u-boot did.. https://git.beagleboard.org/beagleboard/BeagleBoard-DeviceTrees/-/blob/v5.10.x-ti-unified/src/arm/am335x-boneblue.dts?ref_type=heads#L513

**Comment by ghost** [comment]
Just verified, the delete-property line needs to be present in order to shutdown the blue.

I don't know why this contradicts the post in the original commit.

Pushed the reset button and restored previous state. No damage seen.

EDIT: This info was wrong, please ignore this post.

**Comment by ghost** [comment]
Interesting side-note via dmesg:
```
$ dmesg | grep rtc
[    4.781728] omap_rtc 44e3e000.rtc: already running
[    4.783081] omap_rtc 44e3e000.rtc: registered as rtc0
[    4.783149] omap_rtc 44e3e000.rtc: setting system clock to 2023-12-12T19:05:43 UTC (1702407943)
[   46.031368] PM: bootloader does not support rtc-only!
```

There is something fishy about this property. The 4.14 dts did not delete it.
https://github.com/beagleboard/librobotcontrol/blob/master/device_tree/dtb-4.14-ti/am335x-boneblue.dts#L527

Maybe some combination with U-Boot is required.

**Comment by ghost** [comment]
I have tested the ti,pmic-shutdown-controller setting.

First the current state 
with `/delete-property/ ti,pmic-shutdown-controller;`

Steps:
1. Device Running

2. Push Power Button
-> Device shuts down but PWR_LED stays on, e.g. 3V3 is powered

3. Push Power Button
-> Nothing happens. No restart.

4. Push Reset Button
-> Red led above User LEDs stays on, means there is power on `TIMER4_R7`.

5. Push Power Button
-> Device starts.


Second test after removing the line `/delete-property/ ti,pmic-shutdown-controller;`.

1. Device Running

2. Push Power Button
-> Device shuts down but PWR_LED stays on, e.g. 3V3 is powered

3. Push Power Button
-> Nothing happens. No restart.

4. Push Reset Button
-> All Leds turn off. (Also the red one)

5. Push Power Button
-> Device starts.

Essentially, I belive the line should be removed but there is something other missing to have the device actually restart via power button after being shut down by power button.
I'll verify with a debian 10.3 Image later.

**Pull request merged**
